create table airline_covid (
date date,
cancelled_rate_AA int,
total_delay_AA int,
cancelled_rate_DL int,
total_delay_DL int,
cancelled_rate_WN int,
total_delay_WN int,
cancelled_rate_UA int,
total_delay_UA int,
cancelled_rate_NK int,
total_delay_NK int,
cancelled_rate_F9 int,
total_delay_F9 int,
cases int)
