create table airline_covid (
index varchar(30),
date float(0),
cancelled_rate_AA float(0),
total_delay_AA float(0),
cancelled_rate_DL float(0),
total_delay_DL float(0),
cancelled_rate_WN float(0),
total_delay_WN float(0),
cancelled_rate_UA float(0),
total_delay_UA float(0),
cancelled_rate_NK float(0),
total_delay_NK float(0),
cancelled_rate_F9 float(0),
total_delay_F9 float(0),
cases float(0))
